Favorite_Animal = input("What is your favorite animal?\n> ")
print("My favorte animal is " + Favorite_Animal)
Why_Like_Them = input("Why do you like them\n> ") 
print("I like them because "  + Why_Like_Them)
Sounds = input("What sounds dose your animal make\n> ")
print("My animal " + Sounds) 
Live = input("Were dose your animal live\n> ")
print("My anmial lives " + Live)
Fun_fact = input("What is a fun fact about your " + Favorite_Animal + "?\n> ")
print("A fun fact is " + Fun_fact )
Color = input("What color is your " + Favorite_Animal + "?\n> ")
print("its color is " + Color)
Eat = input("What dose your " + Favorite_Animal + " eat?\n> ")
print("My " + Favorite_Animal + " eats " + Eat)
What_Like_Most = input("What do you like most about your animal?\n> ")
print("I like " + What_Like_Most + "the most.")
another_animal = input("Do you have any other favort animals?\n> ")
print("I also like " + another_animal)
